wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.20
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1657745682
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 13
      - 16
      4: 3.8.10
      5: 0.12.20
      8:
      - 5
arch:
  desc: null
  value: vit_large
batch_size:
  desc: null
  value: 32
classifier_type:
  desc: null
  value: ConvSingleLinear
download_data:
  desc: null
  value: false
epochs:
  desc: null
  value: 100
eval_freq:
  desc: null
  value: 5
lr:
  desc: null
  value: 0.001
n_blocks:
  desc: null
  value: 4
patch_size:
  desc: null
  value: 16
percentage:
  desc: null
  value: 0.1
root:
  desc: null
  value: data
segmentation:
  desc: null
  value: multi
upsample:
  desc: null
  value: nearest
warmup_epochs:
  desc: null
  value: 10
weights:
  desc: null
  value: weights/checkpoint.pth
workers:
  desc: null
  value: 4
